# Generated by Django 3.2.25 on 2024-12-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom_app', '0004_orderplaced_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_payment_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='razorpay_payment_status',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(default='Cash on Delivery', max_length=50),
        ),
    ]
